import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import heroOneBg from '../../public/images/hero-1-bg.jpeg'
import { Container } from '../components/Home/Container'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <section>
          Hello world
        </section>
      </Container>
    </>
  )
}

export default Home
